dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  # - <organization/repo>
  - OpenZeppelin/openzeppelin-contracts@4.4.2

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'

networks:
  rinkeby:
    verify: True
  development:
    verify: False
  mainnet-fork-dev:
    verify: False
  mainnet-fork:
    verify: False
  ganache-local:
    verify: False

